package com.rockwell.mes.phase.eqaigetopcvalues;

/**
 * This file is generated by the PhaseGenerator
 */
import com.datasweep.compatibility.client.Server;
import com.rockwell.mes.services.s88.ifc.processdata.IMESRtPhaseOutputFilter;

/**
 * Generated class definition
 */
public class MESRtPhaseOutputEqAIGetOPCVals0100Filter extends MESGeneratedRtPhaseOutputEqAIGetOPCVals0100Filter //nl
                                                                implements IMESRtPhaseOutputFilter {

    /** Generated attribute definition */
    private static final long serialVersionUID = 1L;

    /**
     * Generated method definition
     *
     * @param server The Server object
     */
    public MESRtPhaseOutputEqAIGetOPCVals0100Filter(Server server) {
        super(server);
    }

    /**
     * Generated method definition
     *
     */
    public MESRtPhaseOutputEqAIGetOPCVals0100Filter() {
        super();
    }
}
