package com.rockwell.scl.filter.at;



/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */


/**
 * Generated filter interface for application table SV_FilterInfo.
 * @ftps.exclude 
 */
public interface IMESSVFilterInfoFilter extends IMESGeneratedSVFilterInfoFilter {
}
