package com.rockwell.scl.filter.at;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 *
 * Please do not modify this file manually !!
 */
import com.datasweep.compatibility.client.MeasuredValue;
import com.datasweep.compatibility.ui.Time;
import com.rockwell.mes.commons.base.ifc.objects.IMESATObject;

/**
 * Generated interface definition for application table SV_FilterInfo.<BR>
 * Application table description: 滤器表
 * 
 * @ftps.exclude  
 */
public interface IMESGeneratedSVFilterInfo extends IMESATObject {

    /** name of the corresponding AT definition */
    public static final String ATDEFINITION_NAME = "SV_FilterInfo";

    /** Generated attribute definition */
    public static final String SQL_TABLE_NAME = SQL_TABLE_NAME_PREFIX + ATDEFINITION_NAME;

    /** Generated property name */
    public static final String PROP_NAME_BATCH = "batch";

    /** Generated column name */
    public static final String SQL_COL_NAME_BATCH = "batch_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_BATCH = "batch";

    /** Generated property name */
    public static final String PROP_NAME_COMMENTS = "comments";

    /** Generated column name */
    public static final String SQL_COL_NAME_COMMENTS = "comments_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_COMMENTS = "comments";

    /** Generated property name */
    public static final String PROP_NAME_CONTINUEUSABLE = "continueUsable";

    /** Generated column name */
    public static final String SQL_COL_NAME_CONTINUEUSABLE = "continueUsable_I";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_CONTINUEUSABLE = "continueUsable";

    /** Generated property name */
    public static final String PROP_NAME_CONTINUEUSABLENOTE = "continueUsableNote";

    /** Generated column name */
    public static final String SQL_COL_NAME_CONTINUEUSABLENOTE = "continueUsableNote_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_CONTINUEUSABLENOTE = "continueUsableNote";

    /** Generated property name */
    public static final String PROP_NAME_CURRENTUSAGECOUNT = "currentUsageCount";

    /** Generated column name */
    public static final String SQL_COL_NAME_CURRENTUSAGECOUNT = "currentUsageCount_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_CURRENTUSAGECOUNT = "currentUsageCount";

    /** Generated property name */
    public static final String PROP_NAME_FILTERAPERTURE = "filterAperture";

    /** Generated column name */
    public static final String SQL_COL_NAME_FILTERAPERTURE = "filterAperture_V";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_FILTERAPERTURE = "filterAperture";

    /** Generated property name */
    public static final String PROP_NAME_FILTEROPENDATE = "filterOpenDate";

    /** Generated column name */
    public static final String SQL_COL_NAME_FILTEROPENDATE_UTC = "filterOpenDate_u";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_FILTEROPENDATE = "filterOpenDate";

    /** Generated property name */
    public static final String PROP_NAME_FILTEROPENDATEEXPIRATION = "filterOpenDateExpiration";

    /** Generated column name */
    public static final String SQL_COL_NAME_FILTEROPENDATEEXPIRATION_UTC = "filterOpenDateExpiration_u";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_FILTEROPENDATEEXPIRATION = "filterOpenDateExpiration";

    /** Generated property name */
    public static final String PROP_NAME_FILTERTYPE = "filterType";

    /** Generated column name */
    public static final String SQL_COL_NAME_FILTERTYPE = "filterType_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_FILTERTYPE = "filterType";

    /** Generated property name */
    public static final String PROP_NAME_HASCOLLECTEDASCONSUME = "hasCollectedAsConsume";

    /** Generated column name */
    public static final String SQL_COL_NAME_HASCOLLECTEDASCONSUME = "hasCollectedAsConsume_I";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_HASCOLLECTEDASCONSUME = "hasCollectedAsConsume";

    /** Generated property name */
    public static final String PROP_NAME_INTEGRITYTESTDURATION = "integrityTestDuration";

    /** Generated column name */
    public static final String SQL_COL_NAME_INTEGRITYTESTDURATION = "integrityTestDuration_V";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_INTEGRITYTESTDURATION = "integrityTestDuration";

    /** Generated property name */
    public static final String PROP_NAME_INTEGRITYTESTEXPIRATION = "integrityTestExpiration";

    /** Generated column name */
    public static final String SQL_COL_NAME_INTEGRITYTESTEXPIRATION_UTC = "integrityTestExpiration_u";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_INTEGRITYTESTEXPIRATION = "integrityTestExpiration";

    /** Generated property name */
    public static final String PROP_NAME_INTEGRITYTESTNOTE = "integrityTestNote";

    /** Generated column name */
    public static final String SQL_COL_NAME_INTEGRITYTESTNOTE = "integrityTestNote_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_INTEGRITYTESTNOTE = "integrityTestNote";

    /** Generated property name */
    public static final String PROP_NAME_INTEGRITYTESTRESULT = "integrityTestResult";

    /** Generated column name */
    public static final String SQL_COL_NAME_INTEGRITYTESTRESULT = "integrityTestResult_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_INTEGRITYTESTRESULT = "integrityTestResult";

    /** Generated property name */
    public static final String PROP_NAME_INTEGRITYTESTVALUE = "integrityTestValue";

    /** Generated column name */
    public static final String SQL_COL_NAME_INTEGRITYTESTVALUE = "integrityTestValue_V";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_INTEGRITYTESTVALUE = "integrityTestValue";

    /** Generated property name */
    public static final String PROP_NAME_MANUFACTURER = "manufacturer";

    /** Generated column name */
    public static final String SQL_COL_NAME_MANUFACTURER = "manufacturer_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MANUFACTURER = "manufacturer";

    /** Generated property name */
    public static final String PROP_NAME_MATERIALNAME = "materialName";

    /** Generated column name */
    public static final String SQL_COL_NAME_MATERIALNAME = "materialName_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MATERIALNAME = "materialName";

    /** Generated property name */
    public static final String PROP_NAME_MATERIALNO = "materialNo";

    /** Generated column name */
    public static final String SQL_COL_NAME_MATERIALNO = "materialNo_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MATERIALNO = "materialNo";

    /** Generated property name */
    public static final String PROP_NAME_MOUNTEQUIPMENT = "mountEquipment";

    /** Generated column name */
    public static final String SQL_COL_NAME_MOUNTEQUIPMENT = "mountEquipment_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MOUNTEQUIPMENT = "mountEquipment";

    /** Generated property name */
    public static final String PROP_NAME_MOUNTLOCATION = "mountLocation";

    /** Generated column name */
    public static final String SQL_COL_NAME_MOUNTLOCATION = "mountLocation_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_MOUNTLOCATION = "mountLocation";

    /** Generated property name */
    public static final String PROP_NAME_OPERATETYPE = "operateType";

    /** Generated column name */
    public static final String SQL_COL_NAME_OPERATETYPE = "operateType_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_OPERATETYPE = "operateType";

    /** Generated property name */
    public static final String PROP_NAME_OPERATOR = "operator";

    /** Generated column name */
    public static final String SQL_COL_NAME_OPERATOR = "operator_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_OPERATOR = "operator";

    /** Generated property name */
    public static final String PROP_NAME_ORDERNUMBER = "orderNumber";

    /** Generated column name */
    public static final String SQL_COL_NAME_ORDERNUMBER = "orderNumber_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_ORDERNUMBER = "orderNumber";

    /** Generated property name */
    public static final String PROP_NAME_PROCESSEDMATERIALNAME = "processedMaterialName";

    /** Generated column name */
    public static final String SQL_COL_NAME_PROCESSEDMATERIALNAME = "processedMaterialName_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_PROCESSEDMATERIALNAME = "processedMaterialName";

    /** Generated property name */
    public static final String PROP_NAME_PROCESSEDMATERIALNO = "processedMaterialNo";

    /** Generated column name */
    public static final String SQL_COL_NAME_PROCESSEDMATERIALNO = "processedMaterialNo_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_PROCESSEDMATERIALNO = "processedMaterialNo";

    /** Generated property name */
    public static final String PROP_NAME_PRODUCTIONLINE = "productionLine";

    /** Generated column name */
    public static final String SQL_COL_NAME_PRODUCTIONLINE = "productionLine_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_PRODUCTIONLINE = "productionLine";

    /** Generated property name */
    public static final String PROP_NAME_RECIPEPATH = "recipePath";

    /** Generated column name */
    public static final String SQL_COL_NAME_RECIPEPATH = "recipePath_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_RECIPEPATH = "recipePath";

    /** Generated property name */
    public static final String PROP_NAME_SERIALNO = "serialNo";

    /** Generated column name */
    public static final String SQL_COL_NAME_SERIALNO = "serialNo_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_SERIALNO = "serialNo";

    /** Generated property name */
    public static final String PROP_NAME_STERBATCH = "sterBatch";

    /** Generated column name */
    public static final String SQL_COL_NAME_STERBATCH = "sterBatch_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STERBATCH = "sterBatch";

    /** Generated property name */
    public static final String PROP_NAME_STERCOUNT = "sterCount";

    /** Generated column name */
    public static final String SQL_COL_NAME_STERCOUNT = "sterCount_I";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STERCOUNT = "sterCount";

    /** Generated property name */
    public static final String PROP_NAME_STERSERIALNUMBER = "sterSerialNumber";

    /** Generated column name */
    public static final String SQL_COL_NAME_STERSERIALNUMBER = "sterSerialNumber_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STERSERIALNUMBER = "sterSerialNumber";

    /** Generated property name */
    public static final String PROP_NAME_STERUPLIMIT = "sterUpLimit";

    /** Generated column name */
    public static final String SQL_COL_NAME_STERUPLIMIT = "sterUpLimit_I";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_STERUPLIMIT = "sterUpLimit";

    /** Generated property name */
    public static final String PROP_NAME_SUBLOT = "sublot";

    /** Generated column name */
    public static final String SQL_COL_NAME_SUBLOT = "sublot_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_SUBLOT = "sublot";

    /** Generated property name */
    public static final String PROP_NAME_SVCODE = "svCode";

    /** Generated column name */
    public static final String SQL_COL_NAME_SVCODE = "svCode_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_SVCODE = "svCode";

    /** Generated property name */
    public static final String PROP_NAME_UNQUALIFIEDINTEGRITYQTY = "unqualifiedIntegrityQty";

    /** Generated column name */
    public static final String SQL_COL_NAME_UNQUALIFIEDINTEGRITYQTY = "unqualifiedIntegrityQty_I";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_UNQUALIFIEDINTEGRITYQTY = "unqualifiedIntegrityQty";

    /** Generated property name */
    public static final String PROP_NAME_UNQUALIFIEDUPLIMIT = "unqualifiedUpLimit";

    /** Generated column name */
    public static final String SQL_COL_NAME_UNQUALIFIEDUPLIMIT = "unqualifiedUpLimit_I";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_UNQUALIFIEDUPLIMIT = "unqualifiedUpLimit";

    /** Generated property name */
    public static final String PROP_NAME_USAGE = "usage";

    /** Generated column name */
    public static final String SQL_COL_NAME_USAGE = "usage_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_USAGE = "usage";

    /** Generated property name */
    public static final String PROP_NAME_USAGECOUNTUPLIMIT = "usageCountUpLimit";

    /** Generated column name */
    public static final String SQL_COL_NAME_USAGECOUNTUPLIMIT = "usageCountUpLimit_I";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_USAGECOUNTUPLIMIT = "usageCountUpLimit";

    /** Generated property name */
    public static final String PROP_NAME_WORKSHOP = "workshop";

    /** Generated column name */
    public static final String SQL_COL_NAME_WORKSHOP = "workshop_S";

    /** 
     * Generated AT column name
     * @ftps.exclude 2 (reason: for internal use only)  
     */
    public static final String COL_NAME_WORKSHOP = "workshop";

    /**
     * Generated getter for column batch.<BR>
     * Column description: 批号
     * 
     * @return the requested value
     */
    public String getBatch();

    /**
     * Generated setter for column batch.<BR>
     * Column description: 批号
     * 
     * @param value The new value to be assigned
     */
    public void setBatch(String value);

    /**
     * Generated getter for column comments.<BR>
     * Column description: 备注
     * 
     * @return the requested value
     */
    public String getComments();

    /**
     * Generated setter for column comments.<BR>
     * Column description: 备注
     * 
     * @param value The new value to be assigned
     */
    public void setComments(String value);

    /**
     * Generated getter for column continueUsable.<BR>
     * Column description: 是否继续使用
     * 
     * @return the requested value
     */
    public Long getContinueUsable();

    /**
     * Generated setter for column continueUsable.<BR>
     * Column description: 是否继续使用
     * 
     * @param value The new value to be assigned
     */
    public void setContinueUsable(Long value);

    /**
     * Generated getter for column continueUsableNote.<BR>
     * Column description: 是否继续使用备注
     * 
     * @return the requested value
     */
    public String getContinueUsableNote();

    /**
     * Generated setter for column continueUsableNote.<BR>
     * Column description: 是否继续使用备注
     * 
     * @param value The new value to be assigned
     */
    public void setContinueUsableNote(String value);

    /**
     * Generated getter for column currentUsageCount.<BR>
     * Column description: 当前使用次数
     * 
     * @return the requested value
     */
    public String getCurrentUsageCount();

    /**
     * Generated setter for column currentUsageCount.<BR>
     * Column description: 当前使用次数
     * 
     * @param value The new value to be assigned
     */
    public void setCurrentUsageCount(String value);

    /**
     * Generated getter for column filterAperture.<BR>
     * Column description: 滤器孔径
     * 
     * @return the requested value
     */
    public MeasuredValue getFilterAperture();

    /**
     * Generated setter for column filterAperture.<BR>
     * Column description: 滤器孔径
     * 
     * @param value The new value to be assigned
     */
    public void setFilterAperture(MeasuredValue value);

    /**
     * Generated getter for column filterOpenDate.<BR>
     * Column description: 滤器拆封日期
     * 
     * @return the requested value
     */
    public Time getFilterOpenDate();

    /**
     * Generated setter for column filterOpenDate.<BR>
     * Column description: 滤器拆封日期
     * 
     * @param value The new value to be assigned
     */
    public void setFilterOpenDate(Time value);

    /**
     * Generated getter for column filterOpenDateExpiration.<BR>
     * Column description: 滤器拆封有效期至
     * 
     * @return the requested value
     */
    public Time getFilterOpenDateExpiration();

    /**
     * Generated setter for column filterOpenDateExpiration.<BR>
     * Column description: 滤器拆封有效期至
     * 
     * @param value The new value to be assigned
     */
    public void setFilterOpenDateExpiration(Time value);

    /**
     * Generated getter for column filterType.<BR>
     * Column description: 滤器型号
     * 
     * @return the requested value
     */
    public String getFilterType();

    /**
     * Generated setter for column filterType.<BR>
     * Column description: 滤器型号
     * 
     * @param value The new value to be assigned
     */
    public void setFilterType(String value);

    /**
     * Generated getter for column hasCollectedAsConsume.<BR>
     * Column description: 该记录是否已被收集为消耗信息;1：已被收集
     * 
     * @return the requested value
     */
    public Long getHasCollectedAsConsume();

    /**
     * Generated setter for column hasCollectedAsConsume.<BR>
     * Column description: 该记录是否已被收集为消耗信息;1：已被收集
     * 
     * @param value The new value to be assigned
     */
    public void setHasCollectedAsConsume(Long value);

    /**
     * Generated getter for column integrityTestDuration.<BR>
     * Column description: 完整性测试有效时长
     * 
     * @return the requested value
     */
    public MeasuredValue getIntegrityTestDuration();

    /**
     * Generated setter for column integrityTestDuration.<BR>
     * Column description: 完整性测试有效时长
     * 
     * @param value The new value to be assigned
     */
    public void setIntegrityTestDuration(MeasuredValue value);

    /**
     * Generated getter for column integrityTestExpiration.<BR>
     * Column description: 完整性测试有效期至
     * 
     * @return the requested value
     */
    public Time getIntegrityTestExpiration();

    /**
     * Generated setter for column integrityTestExpiration.<BR>
     * Column description: 完整性测试有效期至
     * 
     * @param value The new value to be assigned
     */
    public void setIntegrityTestExpiration(Time value);

    /**
     * Generated getter for column integrityTestNote.<BR>
     * Column description: 完整性测试备注1
     * 
     * @return the requested value
     */
    public String getIntegrityTestNote();

    /**
     * Generated setter for column integrityTestNote.<BR>
     * Column description: 完整性测试备注1
     * 
     * @param value The new value to be assigned
     */
    public void setIntegrityTestNote(String value);

    /**
     * Generated getter for column integrityTestResult.<BR>
     * Column description: 完整性测试结果
     * 
     * @return the requested value
     */
    public String getIntegrityTestResult();

    /**
     * Generated setter for column integrityTestResult.<BR>
     * Column description: 完整性测试结果
     * 
     * @param value The new value to be assigned
     */
    public void setIntegrityTestResult(String value);

    /**
     * Generated getter for column integrityTestValue.<BR>
     * Column description: 完整性测试值
     * 
     * @return the requested value
     */
    public MeasuredValue getIntegrityTestValue();

    /**
     * Generated setter for column integrityTestValue.<BR>
     * Column description: 完整性测试值
     * 
     * @param value The new value to be assigned
     */
    public void setIntegrityTestValue(MeasuredValue value);

    /**
     * Generated getter for column manufacturer.<BR>
     * Column description: 生产厂家
     * 
     * @return the requested value
     */
    public String getManufacturer();

    /**
     * Generated setter for column manufacturer.<BR>
     * Column description: 生产厂家
     * 
     * @param value The new value to be assigned
     */
    public void setManufacturer(String value);

    /**
     * Generated getter for column materialName.<BR>
     * Column description: 物料名称
     * 
     * @return the requested value
     */
    public String getMaterialName();

    /**
     * Generated setter for column materialName.<BR>
     * Column description: 物料名称
     * 
     * @param value The new value to be assigned
     */
    public void setMaterialName(String value);

    /**
     * Generated getter for column materialNo.<BR>
     * Column description: 物料编码
     * 
     * @return the requested value
     */
    public String getMaterialNo();

    /**
     * Generated setter for column materialNo.<BR>
     * Column description: 物料编码
     * 
     * @param value The new value to be assigned
     */
    public void setMaterialNo(String value);

    /**
     * Generated getter for column mountEquipment.<BR>
     * Column description: 设备编码
     * 
     * @return the requested value
     */
    public String getMountEquipment();

    /**
     * Generated setter for column mountEquipment.<BR>
     * Column description: 设备编码
     * 
     * @param value The new value to be assigned
     */
    public void setMountEquipment(String value);

    /**
     * Generated getter for column mountLocation.<BR>
     * Column description: 安装位置
     * 
     * @return the requested value
     */
    public String getMountLocation();

    /**
     * Generated setter for column mountLocation.<BR>
     * Column description: 安装位置
     * 
     * @param value The new value to be assigned
     */
    public void setMountLocation(String value);

    /**
     * Generated getter for column operateType.<BR>
     * Column description: 操作类型：主数据维护、灭菌、使用、完整性测试
     * 
     * @return the requested value
     */
    public String getOperateType();

    /**
     * Generated setter for column operateType.<BR>
     * Column description: 操作类型：主数据维护、灭菌、使用、完整性测试
     * 
     * @param value The new value to be assigned
     */
    public void setOperateType(String value);

    /**
     * Generated getter for column operator.<BR>
     * Column description: 操作人
     * 
     * @return the requested value
     */
    public String getOperator();

    /**
     * Generated setter for column operator.<BR>
     * Column description: 操作人
     * 
     * @param value The new value to be assigned
     */
    public void setOperator(String value);

    /**
     * Generated getter for column orderNumber.<BR>
     * Column description: 工单号
     * 
     * @return the requested value
     */
    public String getOrderNumber();

    /**
     * Generated setter for column orderNumber.<BR>
     * Column description: 工单号
     * 
     * @param value The new value to be assigned
     */
    public void setOrderNumber(String value);

    /**
     * Generated getter for column processedMaterialName.<BR>
     * Column description: 过滤物料名称
     * 
     * @return the requested value
     */
    public String getProcessedMaterialName();

    /**
     * Generated setter for column processedMaterialName.<BR>
     * Column description: 过滤物料名称
     * 
     * @param value The new value to be assigned
     */
    public void setProcessedMaterialName(String value);

    /**
     * Generated getter for column processedMaterialNo.<BR>
     * Column description: 过滤物料编码
     * 
     * @return the requested value
     */
    public String getProcessedMaterialNo();

    /**
     * Generated setter for column processedMaterialNo.<BR>
     * Column description: 过滤物料编码
     * 
     * @param value The new value to be assigned
     */
    public void setProcessedMaterialNo(String value);

    /**
     * Generated getter for column productionLine.<BR>
     * Column description: 产线
     * 
     * @return the requested value
     */
    public String getProductionLine();

    /**
     * Generated setter for column productionLine.<BR>
     * Column description: 产线
     * 
     * @param value The new value to be assigned
     */
    public void setProductionLine(String value);

    /**
     * Generated getter for column recipePath.<BR>
     * Column description: 使用的路径（使用的工序、单位工序、操作、步骤组成的路径）
     * 
     * @return the requested value
     */
    public String getRecipePath();

    /**
     * Generated setter for column recipePath.<BR>
     * Column description: 使用的路径（使用的工序、单位工序、操作、步骤组成的路径）
     * 
     * @param value The new value to be assigned
     */
    public void setRecipePath(String value);

    /**
     * Generated getter for column serialNo.<BR>
     * Column description: 滤器序列号
     * 
     * @return the requested value
     */
    public String getSerialNo();

    /**
     * Generated setter for column serialNo.<BR>
     * Column description: 滤器序列号
     * 
     * @param value The new value to be assigned
     */
    public void setSerialNo(String value);

    /**
     * Generated getter for column sterBatch.<BR>
     * Column description: 灭菌批号
     * 
     * @return the requested value
     */
    public String getSterBatch();

    /**
     * Generated setter for column sterBatch.<BR>
     * Column description: 灭菌批号
     * 
     * @param value The new value to be assigned
     */
    public void setSterBatch(String value);

    /**
     * Generated getter for column sterCount.<BR>
     * Column description: 已灭菌次数
     * 
     * @return the requested value
     */
    public Long getSterCount();

    /**
     * Generated setter for column sterCount.<BR>
     * Column description: 已灭菌次数
     * 
     * @param value The new value to be assigned
     */
    public void setSterCount(Long value);

    /**
     * Generated getter for column sterSerialNumber.<BR>
     * Column description: 灭菌流水号
     * 
     * @return the requested value
     */
    public String getSterSerialNumber();

    /**
     * Generated setter for column sterSerialNumber.<BR>
     * Column description: 灭菌流水号
     * 
     * @param value The new value to be assigned
     */
    public void setSterSerialNumber(String value);

    /**
     * Generated getter for column sterUpLimit.<BR>
     * Column description: 灭菌最大次数
     * 
     * @return the requested value
     */
    public Long getSterUpLimit();

    /**
     * Generated setter for column sterUpLimit.<BR>
     * Column description: 灭菌最大次数
     * 
     * @param value The new value to be assigned
     */
    public void setSterUpLimit(Long value);

    /**
     * Generated getter for column sublot.<BR>
     * Column description: 子批次号
     * 
     * @return the requested value
     */
    public String getSublot();

    /**
     * Generated setter for column sublot.<BR>
     * Column description: 子批次号
     * 
     * @param value The new value to be assigned
     */
    public void setSublot(String value);

    /**
     * Generated getter for column svCode.<BR>
     * Column description: 科兴编号
     * 
     * @return the requested value
     */
    public String getSvCode();

    /**
     * Generated setter for column svCode.<BR>
     * Column description: 科兴编号
     * 
     * @param value The new value to be assigned
     */
    public void setSvCode(String value);

    /**
     * Generated getter for column unqualifiedIntegrityQty.<BR>
     * Column description: 完整性测试连续不合格次数
     * 
     * @return the requested value
     */
    public Long getUnqualifiedIntegrityQty();

    /**
     * Generated setter for column unqualifiedIntegrityQty.<BR>
     * Column description: 完整性测试连续不合格次数
     * 
     * @param value The new value to be assigned
     */
    public void setUnqualifiedIntegrityQty(Long value);

    /**
     * Generated getter for column unqualifiedUpLimit.<BR>
     * Column description: 完整性测试连续不合格最大次数
     * 
     * @return the requested value
     */
    public Long getUnqualifiedUpLimit();

    /**
     * Generated setter for column unqualifiedUpLimit.<BR>
     * Column description: 完整性测试连续不合格最大次数
     * 
     * @param value The new value to be assigned
     */
    public void setUnqualifiedUpLimit(Long value);

    /**
     * Generated getter for column usage.<BR>
     * Column description: 用途
     * 
     * @return the requested value
     */
    public String getUsage();

    /**
     * Generated setter for column usage.<BR>
     * Column description: 用途
     * 
     * @param value The new value to be assigned
     */
    public void setUsage(String value);

    /**
     * Generated getter for column usageCountUpLimit.<BR>
     * Column description: 最大使用次数
     * 
     * @return the requested value
     */
    public Long getUsageCountUpLimit();

    /**
     * Generated setter for column usageCountUpLimit.<BR>
     * Column description: 最大使用次数
     * 
     * @param value The new value to be assigned
     */
    public void setUsageCountUpLimit(Long value);

    /**
     * Generated getter for column workshop.<BR>
     * Column description: 车间
     * 
     * @return the requested value
     */
    public String getWorkshop();

    /**
     * Generated setter for column workshop.<BR>
     * Column description: 车间
     * 
     * @param value The new value to be assigned
     */
    public void setWorkshop(String value);

}