package com.rockwell.scl.filter.at;



/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.rockwell.mes.commons.base.ifc.objects.IMESObject;



/**
 * Generated interface definition for application table SV_FilterInfo.
 * Application table description: 滤器表<br>
 * @ftps.exclude 
 */
public interface IMESSVFilterInfo extends IMESGeneratedSVFilterInfo {
}