package com.rockwell.scl.filter.at;



/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.datasweep.compatibility.client.Server;



/**
 * Generated filter class for application table SV_FilterInfo.
 * @author RWang18
 */
public class MESSVFilterInfoFilter extends MESGeneratedSVFilterInfoFilter //nl
                                              implements IMESSVFilterInfoFilter {

    /** Generated attribute definition */
    private static final long serialVersionUID = 1L;

    /**
     * Generated constructor
     *
     * @param server The Server object
     */
    public MESSVFilterInfoFilter(Server server) {
        super(server);
    }

    /**
     * Generated default constructor
     */
    public MESSVFilterInfoFilter() {
        super();
    }

    /**
     * Generated method definition
     * 
     * @return the filter object
     */
    public static IMESSVFilterInfoFilter createFilter() {
        return new MESSVFilterInfoFilter();
    }

}