package com.rockwell.scl.filter.at;



/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.datasweep.compatibility.client.ATRow;



/**
 * Generated class definition for application table SV_FilterInfo.
 * Application table description: 滤器表
 */
public class MESSVFilterInfo extends MESGeneratedSVFilterInfo //nl
                                        implements IMESSVFilterInfo {

    /**
     * Generated constructor
     *
     * @param key The key of the ATRow to load.
     */
    public MESSVFilterInfo(long key) {
        super(key);
    }

    /**
     * Generated constructor
     *
     * @param source the source to copy.
     */
    public MESSVFilterInfo(MESSVFilterInfo source) {
        super(source);
    }

    /**
     * Generated constructor
     *
     * @param baseATRow The ATRow to wrap.
     */
    public MESSVFilterInfo(ATRow baseATRow) {
        super(baseATRow);
    }

    /**
     * Generated default constructor
     */
    public MESSVFilterInfo() {
        super();
    }

}
