package com.rockwell.scl.phase.opcrealtimetagtrend0010;

/**
 * This file is generated by the PhaseGenerator
 *
 * Please do not modify this file manually !!
 */

import com.datasweep.compatibility.client.ATRow;
import com.datasweep.compatibility.client.Response;
import com.rockwell.mes.services.s88.ifc.processdata.MESRtPhaseData;

import com.rockwell.mes.commons.base.ifc.utility.StringUtilsEx;

 /**
 * Generated class definition
 * <br/>Application table: SV_PhDatOpcRTTagTrend0010
 */
public abstract class MESGeneratedRtPhaseDataOpcRTTagTrend0010
 extends MESRtPhaseData {

    /** Generated attribute definition */
    protected static final String ATDEFINITION_NAME = "SV_PhDatOpcRTTagTrend0010";


    @Override
    public String getATDefinitionName() {
        return ATDEFINITION_NAME;
    }

    /**
     * Generated constructor
     *
     * @param key The key of the ATRow to load.
     */
    public MESGeneratedRtPhaseDataOpcRTTagTrend0010(long key) {
        super(key);
    }

    /**
     * Generated copy constructor
     *
     * @param source the source to copy.
     */
    public MESGeneratedRtPhaseDataOpcRTTagTrend0010(MESGeneratedRtPhaseDataOpcRTTagTrend0010 source) {
        super(source);
    }

    /**
     * Generated constructor
     *
     * @param baseATRow The ATRow to wrap.
     */
    public MESGeneratedRtPhaseDataOpcRTTagTrend0010(ATRow baseATRow) {
        super(baseATRow);
    }

    /**
     * Generated constructor
     */
    public MESGeneratedRtPhaseDataOpcRTTagTrend0010() {
        super();
    }

    @Override
    protected void synchronizeAfterATRowRefresh() {
        super.synchronizeAfterATRowRefresh();
    }    
    
    /**
     * Generated method definition
     *
     * @return the requested value
     */
    public String getEquipmentId() {
        return StringUtilsEx.decodeStringForUI((String) this.dgtATRow.getValue("SV_equipmentId"));
    }

    /**
     * Generated method definition
     *
     * @param value The new value to be assigned
     */
    public void setEquipmentId(String value) {
        String oldValue = this.getEquipmentId();
        this.dgtATRow.setValue("SV_equipmentId", StringUtilsEx.encodeStringForDB(value));
        pcs.firePropertyChange("equipmentId", oldValue, value);
    }
    
    /**
     * Generated method definition
     *
     * @return the requested value
     */
    public String getEquipmentProperty() {
        return StringUtilsEx.decodeStringForUI((String) this.dgtATRow.getValue("SV_equipmentProperty"));
    }

    /**
     * Generated method definition
     *
     * @param value The new value to be assigned
     */
    public void setEquipmentProperty(String value) {
        String oldValue = this.getEquipmentProperty();
        this.dgtATRow.setValue("SV_equipmentProperty", StringUtilsEx.encodeStringForDB(value));
        pcs.firePropertyChange("equipmentProperty", oldValue, value);
    }
    
    @Override
    protected Response prepareATRowForSave() {
        // Check if transient references are valid and store the corresponding keys in the ATRow:
        Response res = super.prepareATRowForSave();

        return res;
    }

}
