package com.rockwell.scl.phase.opcrealtimetagtrend0010;

/**
 * This file is generated by the PhaseLibManager
 */
import com.datasweep.compatibility.client.ATRow;
import com.rockwell.mes.services.s88.ifc.processdata.IMESRtPhaseData;

/**
 * Generated class definition
 */
public class MESRtPhaseDataOpcRTTagTrend0010 extends MESGeneratedRtPhaseDataOpcRTTagTrend0010 //
                                                  implements IMESRtPhaseData {

    /**
     * Generated method definition
     *
     * @param key The key of the ATRow to load.
     */
    public MESRtPhaseDataOpcRTTagTrend0010(long key) {
        super(key);
    }

    /**
     * Generated method definition
     *
     * @param source the source to copy.
     */
    public MESRtPhaseDataOpcRTTagTrend0010(MESRtPhaseDataOpcRTTagTrend0010 source) {
        super(source);
    }

    /**
     * Generated method definition
     *
     * @param baseATRow The ATRow to wrap.
     */
    public MESRtPhaseDataOpcRTTagTrend0010(ATRow baseATRow) {
        super(baseATRow);
    }

    /**
     * Generated method definition
     *
     */
    public MESRtPhaseDataOpcRTTagTrend0010() {
        super();
    }

}
